language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mongodb

before_script: 
  - sleep 15
  - mongo horizontlaravel --eval 'db.addUser("travis", "test");'
  - composer install

script:
  - php artisan migrate
  - php artisan db:seed



