language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

services:
  - mongodb

before_script: 
  - sleep 15
  - mongo horizontlaravel --eval 'db.addUser("travis", "test");'
  - composer install
  - vendor/bin/phpunit

script:
   - php artisan migrate --no-interaction
   - php artisan db:seed --no-interaction



