language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services:
  #- mongodb
  - mysql

before_script: 
  - sleep 15
  #- mongo horizontlaravel --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS horizontlaravel;'
  - composer install
  - php artisan serve > /dev/null 2>&1 &

script:
   - php artisan migrate --no-interaction --force
   - php artisan db:seed --no-interaction --force
   - export INSTALLED=YES
   - vendor/bin/phpunit resources/tests/unit/ --coverage-clover reports/coverage.xml
   - if [ -f "reports/coverage.xml" ] && [  -z ${CODACY_PROJECT_TOKEN+x} ]; then vendor/bin/codacycoverage clover reports/coverage.xml; fi
   - php artisan horizontcms:version
